// FOR GLOBAL CRYPTO STATS

export const FETCH_GLOBAL_STATS_START = 'FETCH_GLOBAL_STATS_START';
export const FETCH_GLOBAL_STATS_SUCCESS = 'FETCH_GLOBAL_STATS_SUCCESS';
export const FETCH_GLOBAL_STATS_FAIL = 'FETCH_GLOBAL_STATS_FAIL';
