// FOR GLOBAL CRYPTO STATS

export const ActionTypes = {
  FETCH_GLOBAL_STATS_START: 'FETCH_GLOBAL_STATS_START',
  FETCH_GLOBAL_STATS_SUCCESS: 'FETCH_GLOBAL_STATS_SUCCESS',
  FETCH_GLOBAL_STATS_FAIL: 'FETCH_GLOBAL_STATS_FAIL',
};
